Repository AutoDarkMode/Windows-Auto-Night-Mode, pull requests merged in 2025-09, with the labels that each got.

#1030 Feat: HWND broadcast dwm refresh
  AutoDarkModeApp/AutoDarkModeApp.csproj
  AutoDarkModeApp/Strings/ja/Resources.resw
  AutoDarkModeApp/Strings/zh-hans/Resources.resw
  AutoDarkModeApp/ViewModels/SettingsViewModel.cs
  AutoDarkModeApp/Views/SettingsPage.xaml
  AutoDarkModeLib/Configs/AdmConfig.cs
  AutoDarkModeSvc/AutoDarkModeSvc.csproj
  AutoDarkModeSvc/Core/ComponentManager.cs
  AutoDarkModeSvc/Core/ThemeManager.cs
  AutoDarkModeSvc/Handlers/DwmRefreshHandler.cs
  AutoDarkModeSvc/Handlers/ThemeFiles/ThemeFile.cs
  AutoDarkModeSvc/Handlers/ThemeHandler.cs
  AutoDarkModeSvc/Handlers/WallpaperHandler.cs
  AutoDarkModeSvc/Interfaces/ISwitchComponent.cs
  AutoDarkModeSvc/Service.cs
  AutoDarkModeSvc/SwitchComponents/Base/AppsSwitchThemeFile.cs
  AutoDarkModeSvc/SwitchComponents/Base/ColorizationSwitch.cs
  AutoDarkModeSvc/SwitchComponents/Base/SystemSwitchThemeFile.cs
  AutoDarkModeSvc/SwitchComponents/Base/WallpaperSwitchThemeFile.cs
  AutoDarkModeSvc/SwitchComponents/BaseComponent.cs
  adm-updater-rs/Cargo.lock
  adm-updater-rs/Cargo.toml
  adm-updater-rs/src/io_v3.rs
Labels: area-windows themes

#1037 Feature: Allow setting Ignore Color flag in theme mode
  AutoDarkModeApp/Strings/ar/Resources.resw
  AutoDarkModeApp/Strings/cs/Resources.resw
  AutoDarkModeApp/Strings/de/Resources.resw
  AutoDarkModeApp/Strings/el-gr/Resources.resw
  AutoDarkModeApp/Strings/en-us/Resources.resw
  AutoDarkModeApp/Strings/es/Resources.resw
  AutoDarkModeApp/Strings/fa/Resources.resw
  AutoDarkModeApp/Strings/fr/Resources.resw
  AutoDarkModeApp/Strings/he/Resources.resw
  AutoDarkModeApp/Strings/hu/Resources.resw
  AutoDarkModeApp/Strings/id/Resources.resw
  AutoDarkModeApp/Strings/it/Resources.resw
  AutoDarkModeApp/Strings/ja/Resources.resw
  AutoDarkModeApp/Strings/ko/Resources.resw
  AutoDarkModeApp/Strings/nb-no/Resources.resw
  AutoDarkModeApp/Strings/nl/Resources.resw
  AutoDarkModeApp/Strings/pl/Resources.resw
  AutoDarkModeApp/Strings/pt-br/Resources.resw
  AutoDarkModeApp/Strings/pt-pt/Resources.resw
  AutoDarkModeApp/Strings/ro/Resources.resw
  AutoDarkModeApp/Strings/ru/Resources.resw
  AutoDarkModeApp/Strings/sr/Resources.resw
  AutoDarkModeApp/Strings/sv/Resources.resw
  AutoDarkModeApp/Strings/tr/Resources.resw
  AutoDarkModeApp/Strings/uk/Resources.resw
  AutoDarkModeApp/Strings/vi/Resources.resw
  AutoDarkModeApp/Strings/zh-hans/Resources.resw
  AutoDarkModeApp/Strings/zh-hant/Resources.resw
  AutoDarkModeApp/ViewModels/SystemAreasViewModel.cs
  AutoDarkModeApp/ViewModels/ThemePickerViewModel.cs
  AutoDarkModeApp/Views/SystemAreasPage.xaml
  AutoDarkModeApp/Views/ThemePickerPage.xaml
  AutoDarkModeLib/ComponentSettings/Base/SystemSwitchSettings.cs
  AutoDarkModeLib/Enums.cs
  AutoDarkModeSvc/AutoDarkModeSvc.csproj
  AutoDarkModeSvc/Core/ComponentManager.cs
  AutoDarkModeSvc/Core/GlobalState.cs
  AutoDarkModeSvc/Core/PostponeManager.cs
  AutoDarkModeSvc/Core/ThemeManager.cs
  AutoDarkModeSvc/Events/SwitchEventArgs.cs
  AutoDarkModeSvc/Governors/TimeSwitchGovernor.cs
  AutoDarkModeSvc/Handlers/DwmRefreshHandler.cs
  AutoDarkModeSvc/Handlers/IThemeManager2/Tm2Handler.cs
  AutoDarkModeSvc/Handlers/RegistryHandler.cs
  AutoDarkModeSvc/Handlers/ThemeHandler.cs
  AutoDarkModeSvc/Service.cs
  AutoDarkModeSvc/SwitchComponents/Base/AccentColorSwitch.cs
  AutoDarkModeSvc/SwitchComponents/Base/SystemSwitch.cs
  AutoDarkModeSvc/SwitchComponents/Base/SystemSwitchThemeFile.cs
  AutoDarkModeSvc/SwitchComponents/Base/TaskbarColorSwitch.cs
Labels: area-windows themes

#1036 Feature: Decouple Taskbar Accent Color from System Component
  AutoDarkModeApp/ViewModels/SystemAreasViewModel.cs
  AutoDarkModeApp/Views/SystemAreasPage.xaml
  AutoDarkModeLib/ComponentSettings/Base/SystemSwitchSettings.cs
  AutoDarkModeLib/Enums.cs
  AutoDarkModeSvc/Core/ComponentManager.cs
  AutoDarkModeSvc/Core/GlobalState.cs
  AutoDarkModeSvc/Core/PostponeManager.cs
  AutoDarkModeSvc/Core/ThemeManager.cs
  AutoDarkModeSvc/Events/SwitchEventArgs.cs
  AutoDarkModeSvc/Governors/TimeSwitchGovernor.cs
  AutoDarkModeSvc/Handlers/DwmRefreshHandler.cs
  AutoDarkModeSvc/Handlers/RegistryHandler.cs
  AutoDarkModeSvc/Handlers/ThemeHandler.cs
  AutoDarkModeSvc/Service.cs
  AutoDarkModeSvc/SwitchComponents/Base/AccentColorSwitch.cs
  AutoDarkModeSvc/SwitchComponents/Base/SystemSwitch.cs
  AutoDarkModeSvc/SwitchComponents/Base/SystemSwitchThemeFile.cs
  AutoDarkModeSvc/SwitchComponents/Base/TaskbarColorSwitch.cs
Labels: area-UX, area-winui3, area-windows themes

#1027 Fix: SettingsCard header be cut off
  AutoDarkModeApp/Views/WallpaperPickerPage.xaml
Labels: area-UX, area-winui3

#1058 Fix: Configuration watcher isn't working properly
  AutoDarkModeApp/Utils/Handlers/StateUpdateHandler.cs
  AutoDarkModeApp/ViewModels/TimeViewModel.cs
Labels: area-winui3

#1060 Code quality: System Areas page's supplement
  AutoDarkModeApp/Views/SystemAreasPage.xaml
Labels: area-winui3

#1062 Code quality: System Areas page's supplement patch2
  AutoDarkModeApp/ViewModels/SystemAreasViewModel.cs
  AutoDarkModeApp/Views/SystemAreasPage.xaml
Labels: area-winui3

#1059 Regroup System Area Configuration Items Pt2
  AutoDarkModeApp/Strings/ar/Resources.resw
  AutoDarkModeApp/Strings/cs/Resources.resw
  AutoDarkModeApp/Strings/de/Resources.resw
  AutoDarkModeApp/Strings/el-gr/Resources.resw
  AutoDarkModeApp/Strings/en-us/Resources.resw
  AutoDarkModeApp/Strings/es/Resources.resw
  AutoDarkModeApp/Strings/fa/Resources.resw
  AutoDarkModeApp/Strings/fr/Resources.resw
  AutoDarkModeApp/Strings/he/Resources.resw
  AutoDarkModeApp/Strings/hu/Resources.resw
  AutoDarkModeApp/Strings/id/Resources.resw
  AutoDarkModeApp/Strings/it/Resources.resw
  AutoDarkModeApp/Strings/ja/Resources.resw
  AutoDarkModeApp/Strings/ko/Resources.resw
  AutoDarkModeApp/Strings/nb-no/Resources.resw
  AutoDarkModeApp/Strings/nl/Resources.resw
  AutoDarkModeApp/Strings/pl/Resources.resw
  AutoDarkModeApp/Strings/pt-br/Resources.resw
  AutoDarkModeApp/Strings/pt-pt/Resources.resw
  AutoDarkModeApp/Strings/ro/Resources.resw
  AutoDarkModeApp/Strings/ru/Resources.resw
  AutoDarkModeApp/Strings/sr/Resources.resw
  AutoDarkModeApp/Strings/sv/Resources.resw
  AutoDarkModeApp/Strings/tr/Resources.resw
  AutoDarkModeApp/Strings/uk/Resources.resw
  AutoDarkModeApp/Strings/vi/Resources.resw
  AutoDarkModeApp/Strings/zh-hans/Resources.resw
  AutoDarkModeApp/Strings/zh-hant/Resources.resw
  AutoDarkModeApp/ViewModels/SystemAreasViewModel.cs
  AutoDarkModeApp/Views/SystemAreasPage.xaml
  AutoDarkModeSvc/AutoDarkModeSvc.csproj
Labels: area-winui3

#1067 Feat: Permit Spotlight in Backend for 22H2 ubr 4239
  AutoDarkModeLib/Enums.cs
  AutoDarkModeSvc/SwitchComponents/Base/WallpaperSwitch.cs
Labels: area-windows themes

#1069 Code quality: Remove Energy saver mitigation from App and Svc
  AutoDarkModeApp/Strings/ar/Resources.resw
  AutoDarkModeApp/Strings/cs/Resources.resw
  AutoDarkModeApp/Strings/de/Resources.resw
  AutoDarkModeApp/Strings/el-gr/Resources.resw
  AutoDarkModeApp/Strings/en-us/Resources.resw
  AutoDarkModeApp/Strings/es/Resources.resw
  AutoDarkModeApp/Strings/fa/Resources.resw
  AutoDarkModeApp/Strings/fr/Resources.resw
  AutoDarkModeApp/Strings/he/Resources.resw
  AutoDarkModeApp/Strings/hu/Resources.resw
  AutoDarkModeApp/Strings/id/Resources.resw
  AutoDarkModeApp/Strings/it/Resources.resw
  AutoDarkModeApp/Strings/ja/Resources.resw
  AutoDarkModeApp/Strings/ko/Resources.resw
  AutoDarkModeApp/Strings/nb-no/Resources.resw
  AutoDarkModeApp/Strings/nl/Resources.resw
  AutoDarkModeApp/Strings/pl/Resources.resw
  AutoDarkModeApp/Strings/pt-br/Resources.resw
  AutoDarkModeApp/Strings/pt-pt/Resources.resw
  AutoDarkModeApp/Strings/ro/Resources.resw
  AutoDarkModeApp/Strings/ru/Resources.resw
  AutoDarkModeApp/Strings/sr/Resources.resw
  AutoDarkModeApp/Strings/sv/Resources.resw
  AutoDarkModeApp/Strings/tr/Resources.resw
  AutoDarkModeApp/Strings/uk/Resources.resw
  AutoDarkModeApp/Strings/vi/Resources.resw
  AutoDarkModeApp/Strings/zh-hans/Resources.resw
  AutoDarkModeApp/Strings/zh-hant/Resources.resw
  AutoDarkModeApp/ViewModels/SettingsViewModel.cs
  AutoDarkModeApp/Views/SettingsPage.xaml
  AutoDarkModeLib/Configs/AdmConfig.cs
  AutoDarkModeSvc/Core/ThemeManager.cs
  AutoDarkModeSvc/Handlers/PowerHandler.cs
  AutoDarkModeSvc/Handlers/ThemeHandler.cs
Labels: area-winui3, area-internal
